#!/usr/bin/python
import zipfile, sys, os
CHUNK_SIZE = 0xffff

if len(sys.argv) < 3:
    print >>sys.stderr, "Usage: make-fastwrap-zip IN OUT [additional files to include]"
    exit(1)

IN, OUT = sys.argv[1:3]
ADD_FILES = sys.argv[3:]

outzip = zipfile.ZipFile( OUT, "w",
                          # No compression
                          zipfile.ZIP_STORED )

buf = open( IN, "r" ).read()

n = 0
for i in range(0, len(buf), CHUNK_SIZE):
    zi = zipfile.ZipInfo()
    zi.filename = "fastwrap_%5.5i" % n
    zi.comment = buf[i:i+CHUNK_SIZE]

    outzip.writestr( zi, "File data stored in zip comment!" )
    n += 1

# Store the number of chunks in the main zipfile comment
outzip.comment = str(n)

for fname in ADD_FILES:
    "Add the extra files to the zip file"
    outzip.write( fname, os.path.basename(fname) )

outzip.close()
