#!/bin/bash

if [ -f pyenv.zip ]
    then
    rm -f pyenv.zip
fi

td=`mktemp -d`

cp -r pyenv/* $td
target_zip=`pwd`/pyenv.zip

cd $td

# Remove unecessary files
find -name '.gitignore' | xargs rm -f
find -name '*.pyc' | xargs rm -f

zip -r $target_zip ./
rm -rf $td
