#!/usr/bin/python
import zipfile, sys, os

if len(sys.argv) != 3:
    print >>sys.stderr, "Usage: fastwrap-extract IN OUT"
    exit(1)

IN, OUT = sys.argv[1:]

fz = zipfile.ZipFile( IN, "r" )
of = open(OUT, "w")

comments = {}
for zi in fz.infolist():
    comments[zi.filename] = zi.comment

buf = ""

for n in range(0, int(fz.comment)):
    name = "fastwrap_%5.5i" % n
    if name not in comments:
        raise Exception("Missing chunk")

    of.write( comments[name] )

of.close()
fz.close()
